name: outworking_backend_deploy
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: dependencies install
        run: npm ci
      - name: Build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy connect Server
        env:
          AWS_HOST: ${{secrets.AWS_HOST}}
          AWS_USER: ${{secrets.AWS_USER}}
          ENV_CONTENT: ${{secrets.ENV_CONTENT}}
          PROCESS_NAME: ${{secrets.PROCESS_NAME}}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#        Github Action Runner 설정
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $AWS_HOST >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no $AWS_USER@$AWS_HOST << EOF
            cd /home/ec2-user/outwork/backend
            git pull origin main
            echo "$ENV_CONTENT" > .env
            npm install
            pm2 restart "$PROCESS_NAME"
          EOF
          
          
          

